const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const Folders=require('../src/folders-model.js');
function setup(){
 const listeners={},classes=()=>({add(){},remove(){}}),roots=Folders.LEGACY_ROOTS.map(f=>({...f}));
 const ctx={Folders,folders:Folders.create(Folders.create(roots,'customers','A','a'),'a','Child','child'),notes:[{id:'n',folderId:'a',title:'Title',body:'Content',updated:1,deleted:false}],storageFailed:false,persist:()=>true,revealFolder(){},render(){},toast(){},closeFolderMenu(){},document:{addEventListener:(name,fn)=>listeners[name]=fn},window:{addEventListener(){}}};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../src/drag-drop.js'),'utf8'),ctx);
 function drag(kind,id,destination){const source={dataset:kind==='folder'?{folderId:id}:{noteId:id},classList:classes()};source.closest=q=>q==='[draggable="true"]'?source:null;const target={dataset:{folderDrop:destination},classList:classes()};target.closest=()=>target;const dataTransfer={setData(){}};listeners.dragstart({target:source,dataTransfer,preventDefault(){}});let allowed=false;listeners.dragover({target,dataTransfer,preventDefault(){allowed=true;}});listeners.drop({target,dataTransfer,preventDefault(){}});return allowed;}
 return {ctx,drag};
}
test('drag handlers move notes and folder subtrees into the requested destination',()=>{const {ctx,drag}=setup();assert.equal(drag('note','n','technologies'),true);assert.equal(ctx.notes[0].folderId,'technologies');assert.equal(ctx.notes[0].body,'Content');assert.equal(drag('folder','a','technologies'),true);assert.equal(Folders.path(ctx.folders,'child'),'Technologies / A / Child');assert.equal(drag('folder','a','*'),true);assert.equal(Folders.path(ctx.folders,'child'),'A / Child');});
test('notes can move to the root and back into a folder',()=>{const {ctx,drag}=setup();assert.equal(drag('note','n','*'),true);assert.equal(ctx.notes[0].folderId,null);assert.equal(drag('note','n','a'),true);assert.equal(ctx.notes[0].folderId,'a');});
test('invalid drops and storage failures do not change locations',()=>{const {ctx,drag}=setup();assert.equal(drag('folder','a','child'),false);assert.equal(Folders.path(ctx.folders,'a'),'Customers / A');ctx.persist=()=>false;drag('note','n','technologies');assert.equal(ctx.notes[0].folderId,'a');assert.equal(ctx.notes[0].updated,1);drag('folder','a','technologies');assert.equal(Folders.path(ctx.folders,'a'),'Customers / A');assert.equal(drag('note','n','*'),true);assert.equal(ctx.notes[0].folderId,'a');});
