const {test}=require('node:test');const assert=require('node:assert/strict');const Gantt=require('../src/gantt-model.js');
const task={id:'task',name:'Firewall upgrade',start:'2026-09-07',end:'2026-09-09',progress:25,milestone:false,dependencies:[]};
test('Gantt dates reject impossible dates and tasks reject reversed ranges and invalid progress',()=>{assert.throws(()=>Gantt.day('2026-02-30'));assert.throws(()=>Gantt.validate([{...task,end:'2026-09-06'}]));assert.throws(()=>Gantt.validate([{...task,progress:101}]));assert.throws(()=>Gantt.validate([task,task]));assert.deepEqual(Gantt.validate([task]),[task]);});
test('moving task dates keeps their inclusive duration, including across daylight saving',()=>{const shifted=Gantt.shift({...task,start:'2026-10-31',end:'2026-11-02'},2);assert.equal(shifted.start,'2026-11-02');assert.equal(shifted.end,'2026-11-04');});
test('resizing a task cannot reverse its start and end',()=>{assert.equal(Gantt.shift(task,20,'start').start,task.end);assert.equal(Gantt.shift(task,-20,'end').end,task.start);});
test('timeline includes one-day tasks and clips bars to the visible period',()=>{assert.deepEqual(Gantt.position({...task,end:task.start},Gantt.day(task.start),30),{left:0,width:1,clippedStart:false,clippedEnd:false});assert.deepEqual(Gantt.position(task,Gantt.day('2026-09-08'),1),{left:0,width:1,clippedStart:true,clippedEnd:true});assert.equal(Gantt.position(task,Gantt.day('2026-10-01'),30),null);});

test('dependencies move successors later and preserve duration while rejecting cycles',()=>{const next={...task,id:'next',dependencies:['task'],start:'2026-09-08',end:'2026-09-10'};const planned=Gantt.schedule([next,task]);assert.equal(planned[0].start,'2026-09-10');assert.equal(planned[0].end,'2026-09-12');assert.throws(()=>Gantt.validate([{...task,dependencies:['next']},next]),/loop/);});
test('milestones keep one date when moved and can drive a dependency',()=>{const milestone={...task,milestone:true,end:task.start};const moved=Gantt.shift(milestone,3,'end');assert.equal(moved.start,'2026-09-10');assert.equal(moved.end,moved.start);assert.throws(()=>Gantt.validate([{...task,milestone:true}]));});
const Folders=require('../src/folders-model.js');
test('Gantt folders keep tasks, dependencies, and milestones through moves and backups',()=>{let folders=Folders.create(Folders.ROOTS,'customers','Rollout','chart','gantt');folders.find(f=>f.id==='chart').tasks=Gantt.schedule([task,{...task,id:'launch',name:'Launch',milestone:true,start:'2026-09-11',end:'2026-09-11',dependencies:['task']}]);folders=Folders.move(folders,'chart','technologies');const restored=Folders.load(JSON.parse(JSON.stringify({version:4,folders})),[]);assert.equal(restored.folders.find(f=>f.id==='chart').tasks[1].dependencies[0],'task');assert.equal(restored.folders.find(f=>f.id==='chart').tasks[1].milestone,true);assert.throws(()=>Folders.create(folders,'chart','Nested','nested'));assert.throws(()=>Folders.load({version:4,folders},[{folderId:'chart'}]));const merged=Folders.merge({folders:Folders.ROOTS,notes:[]},{folders,notes:[]});assert.equal(merged.folders.find(f=>f.id==='chart').tasks.length,2);});
