const {test}=require('node:test');const assert=require('node:assert/strict');const Todo=require('../src/todo-model.js');const Folders=require('../src/folders-model.js');
const task={id:'task',title:'Check backups',completed:false,due:'2026-09-10',created:1,parent:null};
test('to-do validation preserves completion and optional dates, rejecting malformed tasks',()=>{assert.deepEqual(Todo.validate([task]),[task]);assert.equal(Todo.validate([{...task,due:null}])[0].due,null);for(const invalid of [{...task,title:' '},{...task,due:'2026-02-30'},{...task,completed:'yes'}])assert.throws(()=>Todo.validate([invalid]));assert.throws(()=>Todo.validate([task,task]));});
test('to-do filters separate completed tasks without changing manual order',()=>{const done={...task,id:'done',completed:true};assert.deepEqual(Todo.select([done,task],'all'),[done,task]);assert.deepEqual(Todo.select([done,task],'active'),[task]);assert.deepEqual(Todo.select([done,task],'completed'),[done]);});
test('to-do pages retain items through folder moves, reloads, and backup merges',()=>{let folders=Folders.create(Folders.LEGACY_ROOTS,'customers','Daily checks','todo','todo');folders.find(f=>f.id==='todo').items=[task];folders=Folders.move(folders,'todo','technologies');const loaded=Folders.load(JSON.parse(JSON.stringify({version:4,folders})),[]);assert.deepEqual(loaded.folders.find(f=>f.id==='todo').items,[task]);const merged=Folders.merge({folders:Folders.LEGACY_ROOTS,notes:[]},{folders:loaded.folders,notes:[]});assert.equal(merged.folders.find(f=>f.id==='todo').kind,'todo');assert.deepEqual(merged.folders.find(f=>f.id==='todo').items,[task]);assert.throws(()=>Folders.create(folders,'todo','Nested','child'));assert.throws(()=>Folders.load({version:4,folders},[{folderId:'todo'}]));});
test('backup merges keep current tasks and add new tasks without duplicates',()=>{assert.deepEqual(Todo.merge([task],[{...task,completed:true},{...task,id:'new'}]),[task,{...task,id:'new'}]);});

test('dragging reorders entire task branches and supports nesting and moving back to root',()=>{const a={...task,id:'a'},b={...task,id:'b'},child={...task,id:'child',parent:'a'};const moved=Todo.move([a,child,b],'a','b','after');assert.deepEqual(moved.map(t=>t.id),['b','a','child']);assert.equal(moved[2].parent,'a');const nested=Todo.move(moved,'a','b','inside');assert.equal(nested.find(t=>t.id==='a').parent,'b');const root=Todo.move(nested,'a',null,'root');assert.equal(root.find(t=>t.id==='a').parent,null);assert.throws(()=>Todo.move(root,'a','child','inside'));});
test('nested filtering retains ancestors and deleting a parent removes its whole branch',()=>{const parent={...task,id:'parent',completed:true},child={...task,id:'child',parent:'parent'};assert.deepEqual(Todo.visible([parent,child],'active').map(e=>[e.item.id,e.depth,e.context]),[['parent',0,true],['child',1,false]]);assert.deepEqual(Todo.remove([parent,child],'parent'),[]);assert.throws(()=>Todo.validate([{...task,parent:'missing'}]));assert.throws(()=>Todo.validate([{...task,parent:task.id}]));});
test('older tasks migrate to root without losing completion or due dates',()=>{const old={...task};delete old.parent;assert.deepEqual(Todo.validate([old]),[task]);});
